defaults: &defaults
  # registration form
  birth_date: true
  address: true
  zip: true
  city: true
  state: true
  # other stuff
  send_email_notification_to_users: true
  automatic_captive_portal_login: true
  mac_address_authentication: false
  # additional languages
  english: true
  italian: true
  spanish: true
  german: true
  slovenian: false
  furlan: false
  
  #ssl_ca_path: '/usr/lib/ssl/certs'

  #piwik_site_id: idsite
  #piwik_url: //piwiki-url.com
  
  # uncomment these if you deploy your app in a sub directory
  # app root dir and static assets host
  #root_dir: '/app'
  #asset_host: 'domain.com/app'

  #sentry_dsn: 'http://public:secret@example.com/project-id'
  
  # check called station id
  check_called_station_id:
    # filter radius accounting sessions older than between_min
    between_min: 10
    # filter radius accounting sessions newer than between_max
    between_max: 60

  spid_required: [
     {Codice-fiscale-SPID: "Codice Fiscale", Shib-Identita-Nome: "Nome", Shib-Identita-Cognome: "Cognome", Shib-Email: "Indirizzo e-mail"} ]
  spid_attributes: [
    {username: "Codice-fiscale-SPID", given_name: "Shib-Identita-Nome", surname: "Shib-Identita-Cognome", email: "Shib-Email", auth_method: "spid"} ]
  spid_options: [
     {:skip_subject_confirmation: true, skip_recipient_check: true, :allowed_clock_drift: 30} ]
  spid_skip_errors: 'Invalid Signature on SAML Response'
  spid_issuer: 'http://idp.domain/entityID'
  spid_redir_url: 'http://www.cineca.it'
  spid_want_assertions_encrypted: true
  spid_redirect_logout: 'https://idp.domain/logout.do'

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
